---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.17.1.100 serasaapp


    - name: Adiciona usuario rodrigomoro
      user:
        name: rodrigomoro
        shell: /bin/bash
        password : $1$pXQa0sl/$JhTfnhiefaPGQFlD4xoem0
        
    - name: Instala pacotes que permitem que o apt seja usado sobre HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - nfs-common
        - git
        - vim
        - nano
        
    - name: Clona reposit贸rio com os arquivos do curso para a HOME do usuario rodrigomoro
      git:
        repo: 'https://github.com/rodrigomororodrigues/newchallenge.git'
        dest: /home/rodrigomoro/ansibleteste
        
    - name: Cria o diret贸rio .ssh
      file:
        path: /home/rodrigomoro/.ssh
        state: directory
        owner: rodrigomoro
        group: rodrigomoro
        mode: '0755'
        
    - name: Cria o diret贸rio data
      file:
        path: /home/rodrigomoro/data
        state: directory
        owner: rodrigomoro
        group: rodrigomoro
        mode: '0755'

    - name: Criando o arquivo 98_rodrigomoro
      copy:
        src: files/98_rodrigmoro
        dest: /etc/sudoers.d
        mode: 0644
        
    - name: Criando o arquivo authorized_keys
      copy:
        src: files/authorized_keys
        dest: /home/rodrigomoro/.ssh/authorized_keys
        owner: rodrigomoro
        group: rodrigomoro
        mode: 0644
   
    - name: Instala pacotes que permitem que o apt seja usado sobre HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - nfs-common
        - vim

    - name: Adiciona uma chave de assinatura apt para o Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona repositorio apt para versao estavel
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Instala o Docker e suas dependencias
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      notify:
        - docker status

    - name: Adiciona o usuario rodrigomoro no grupo docker
      user:
        name: rodrigomoro
        group: docker

    - name: Cria o diret贸rio registry:5000
      file:
        path: /etc/docker/certs.d/registry:5000
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Criando o arquivo ca.crt
      copy:
        src: files/ca.crt
        dest: /etc/docker/certs.d/registry:5000
        owner: rodrigomoro
        group: rodrigomoro
        mode: '0644'
        
    - name: Criando o arquivo daemon.json
      copy:
        src: files/daemon.json
        dest: /etc/docker/
        owner: root
        group: root
        mode: '0644'
   
    - name: Cria o diretorio docker.service.d
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'
        
    - name: Reinicia o Docker
      service:
        name: docker
        daemon_reload: yes
        state: restarted

    - name: Remove swap do arquivo /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Desativa o swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

  handlers:
    - name: docker status
      service: name=docker state=started
